name: GitHub Actions python
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Show event information
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #gpt added this to be smort

      - name: Show repository information
        run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          ls ${{ github.workspace }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup POppler Linux
        run: | 
          sudo apt-get install poppler-utils
      - name: Install Python requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: |
          python pdf_to_png.py
      - name: Add generated file automagically
        run : | 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "PNG generated by actions"
          git push

      - name: Show job status
        run: |
          echo "🍏 This job's status is ${{ job.status }}."
